spring.application.name=review-service

server.port=8082

review.storage.file=reviews.json

prompt.service.url=http://localhost:8081

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html