spring.application.name=review-service

# ===============================
# Server
# ===============================
server.port=8082

# ===============================
# JWT Configuration
# ===============================
jwt.secret=${JWT_SECRET}

# ===============================
# JSON Storage
# ===============================
review.storage.file=reviews.json

# ===============================
# Prompt Service URL
# ===============================
prompt.service.url=http://localhost:8081